"""
Octopus Core Data Models - Pydantic Definitions

This module defines the core data transfer objects (DTOs) for communication
between the Decision Brain (Head) and Execution Tentacles.

These models ensure type safety and clear contract between layers.
"""

from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional, Union
from pydantic import BaseModel, Field, ConfigDict


# ============================================================
# ENUMS
# ============================================================

class TaskPriority(str, Enum):
    """Task priority levels - used by the Brain to prioritize tentacle work"""
    CRITICAL = "critical"    # Must execute immediately
    HIGH = "high"           # Execute soon
    NORMAL = "normal"       # Standard priority
    LOW = "low"             # Can wait

class TaskStatus(str, Enum):
    """Task execution status"""
    PENDING = "pending"           # Queued, not started
    RUNNING = "running"          # Currently executing
    COMPLETED = "completed"       # Successfully finished
    FAILED = "failed"            # Execution failed
    CANCELLED = "cancelled"      # Cancelled by Brain
    RETRYING = "retrying"       # Attempting to recover

class ToolCategory(str, Enum):
    """Categories of tools available to tentacles"""
    WEB_SCRAPING = "web_scraping"
    DATABASE = "database"
    CODE_EXECUTION = "code_execution"
    EMAIL = "email"
    API_CALL = "api_call"
    FILE_SYSTEM = "file_system"
    MESSAGE_QUEUE = "message_queue"
    CUSTOM = "custom"

class PlanStatus(str, Enum):
    """Status of a plan generated by the Brain"""
    DRAFT = "draft"             # Being constructed
    VALIDATED = "validated"      # Passed validation
    APPROVED = "approved"        # Approved by Brain
    REJECTED = "rejected"       # Rejected (ethics/constraints)
    EXECUTING = "executing"     # Currently being executed
    COMPLETED = "completed"      # Successfully completed
    PARTIALLY_COMPLETED = "partially_completed"
    FAILED = "failed"

class ExecutionMode(str, Enum):
    """How the plan should be executed"""
    SEQUENTIAL = "sequential"   # One step at a time
    PARALLEL = "parallel"       # All steps at once
    CONDITIONAL = "conditional" # Based on results


# ============================================================
# TOOL RESULT MODELS (Tentacle → Brain)
# ============================================================

class ToolMetadata(BaseModel):
    """Metadata about the tool that was executed"""
    tool_id: str = Field(..., description="Unique identifier of the tool")
    tool_name: str = Field(..., description="Human-readable tool name")
    category: ToolCategory = Field(..., description="Tool category")
    version: str = Field(default="1.0.0", description="Tool version")
    execution_time_ms: Optional[float] = Field(None, description="Execution time in milliseconds")


class ToolParameter(BaseModel):
    """Definition of a tool parameter"""
    name: str
    type: str
    description: str
    required: bool = True
    default: Optional[Any] = None
    options: Optional[List[str]] = None


class ToolDefinition(BaseModel):
    """Complete definition of an available tool"""
    model_config = ConfigDict(extra='allow')
    
    tool_id: str
    name: str
    description: str
    category: ToolCategory
    parameters: List[ToolParameter] = Field(default_factory=list)
    return_type: str = "any"
    constraints: List[str] = Field(default_factory=list)
    timeout_seconds: int = 60
    rate_limit: Optional[int] = None
    version: str = "1.0.0"


class ToolResult(BaseModel):
    """
    ToolResult - The data package a Tentacle sends back to the Brain.
    
    This is the fundamental "data packet" that flows from Execution → Decision.
    
    Example:
        result = ToolResult(
            tool_id="web_scraper",
            status="success",
            output={"content": "Scraped HTML...", "urls_found": 5}
        )
    """
    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "tool_id": "web_scraper",
                "status": "success",
                "output": {"content": "...", "count": 42},
                "execution_time_ms": 1234.5
            }
        }
    )
    
    # Core identification
    tool_id: str = Field(..., description="Which tool generated this result")
    task_id: str = Field(..., description="Which task this result belongs to")
    
    # Execution status
    status: TaskStatus = Field(..., description="Execution status")
    error: Optional[str] = Field(None, description="Error message if failed")
    error_code: Optional[str] = Field(None, description="Machine-readable error code")
    
    # Output
    output: Optional[Any] = Field(None, description="The actual output data")
    partial_output: Optional[Any] = Field(None, description="Partial results if streaming")
    
    # Metadata
    metadata: Dict[str, Any] = Field(default_factory=dict)
    execution_time_ms: Optional[float] = Field(None, description="Execution duration")
    timestamp: datetime = Field(default_factory=datetime.now)
    
    # Retry information
    retry_count: int = Field(default=0, description="Number of retries attempted")
    max_retries: int = Field(default=3, description="Maximum retries allowed")
    
    # Context
    logs: List[str] = Field(default_factory=list, description="Execution logs")
    warnings: List[str] = Field(default_factory=list, description="Non-fatal warnings")


# ============================================================
# TASK REQUEST MODELS (Brain → Tentacle)
# ============================================================

class TaskConstraints(BaseModel):
    """Constraints and guardrails for task execution"""
    max_execution_time_seconds: Optional[int] = None
    max_cost: Optional[float] = None
    allowed_tools: Optional[List[str]] = None
    blocked_tools: Optional[List[str]] = None
    require_approval_before: Optional[List[str]] = None
    retry_policy: Optional[Dict[str, Any]] = None


class TaskContext(BaseModel):
    """Context information passed with the task"""
    user_id: Optional[str] = None
    session_id: Optional[str] = None
    conversation_history: Optional[List[Dict[str, Any]]] = None
    entity_state: Optional[Dict[str, Any]] = Field(default_factory=dict)
    custom: Optional[Dict[str, Any]] = Field(default_factory=dict)


class TaskRequest(BaseModel):
    """
    TaskRequest - The command packet the Brain sends to the Tentacles.
    
    This is how the Brain tells the Tentacles WHAT to do and HOW to do it.
    
    Key Design Decisions:
    1. Clear task_id for tracking
    2. Explicit parameters (no ambiguity)
    3. Priority for scheduling
    4. Constraints for safety
    5. Context for understanding
    
    Example:
        request = TaskRequest(
            task_id="task_123",
            tool_id="web_scraper",
            parameters={"url": "https://example.com", "selectors": ["h1", "p"]},
            priority="normal"
        )
    """
    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "task_id": "task_abc123",
                "tool_id": "web_scraper",
                "parameters": {"url": "https://example.com"},
                "priority": "normal",
                "constraints": {"max_execution_time_seconds": 30}
            }
        }
    )
    
    # Task identification
    task_id: str = Field(..., description="Unique task identifier (UUID)")
    plan_id: Optional[str] = Field(None, description="Parent plan ID if part of a plan")
    
    # What to execute
    tool_id: str = Field(..., description="Which tool/tentacle to use")
    parameters: Dict[str, Any] = Field(..., description="Tool-specific parameters")
    
    # Priority & scheduling
    priority: TaskPriority = Field(default=TaskPriority.NORMAL)
    
    # Constraints & guardrails
    constraints: TaskConstraints = Field(default_factory=TaskConstraints)
    
    # Context
    context: TaskContext = Field(default_factory=TaskContext)
    
    # Retry configuration
    max_retries: int = Field(default=3, ge=0, le=10)
    retry_delay_seconds: float = Field(default=1.0, ge=0)
    
    # Metadata
    created_at: datetime = Field(default_factory=datetime.now)
    created_by: str = Field(default="brain", description="Who created this task")
    description: Optional[str] = Field(None, description="Human-readable description")
    tags: List[str] = Field(default_factory=list)


# ============================================================
# PLAN MODELS (Brain's Output)
# ============================================================

class StepDependency(BaseModel):
    """Defines dependencies between steps in a plan"""
    depends_on: List[str] = Field(default_factory=list, description="Step IDs this depends on")
    condition: Optional[str] = Field(None, description="Condition for execution")
    timeout_seconds: Optional[int] = None


class ExecutionStep(BaseModel):
    """
    A single step in a plan.
    
    Each step is a discrete unit of work that a Tentacle can execute.
    """
    step_id: str = Field(..., description="Unique step identifier")
    order: int = Field(..., description="Execution order (0-indexed)")
    
    # What to execute
    tool_id: str = Field(..., description="Which tool to use")
    parameters: Dict[str, Any] = Field(default_factory=dict)
    description: str = Field(..., description="What this step does")
    
    # Dependencies
    dependencies: StepDependency = Field(default_factory=StepDependency)
    
    # Expected output schema
    expected_output_type: Optional[str] = None
    output_key: Optional[str] = Field(None, description="Key to store result under")
    
    # On failure
    on_failure: str = Field(default="abort", description="abort|retry|skip")
    max_retries: int = Field(default=3)


class Plan(BaseModel):
    """
    Plan - The complete execution blueprint generated by the Brain.
    
    This is the primary output of the Decision Brain. It contains:
    1. A sequence of steps (ExecutionSteps)
    2. Overall strategy and reasoning
    3. Success criteria
    4. Fallback plans
    
    Example:
        plan = Plan(
            plan_id="plan_xyz",
            objective="Gather competitor pricing data",
            steps=[
                ExecutionStep(step_id="s1", order=0, tool_id="web_scraper", ...),
                ExecutionStep(step_id="s2", order=1, tool_id="data_processor", ...),
            ]
        )
    """
    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "plan_id": "plan_abc",
                "objective": "Analyze market trends",
                "steps": [
                    {
                        "step_id": "s1",
                        "order": 0,
                        "tool_id": "web_scraper",
                        "description": "Scrape market data"
                    }
                ]
            }
        }
    )
    
    # Plan identification
    plan_id: str = Field(..., description="Unique plan identifier")
    
    # What the plan achieves
    objective: str = Field(..., description="High-level objective")
    description: Optional[str] = Field(None, description="Detailed description")
    
    # Steps to execute
    steps: List[ExecutionStep] = Field(..., description="Ordered execution steps")
    execution_mode: ExecutionMode = Field(default=ExecutionMode.SEQUENTIAL)
    
    # Status tracking
    status: PlanStatus = Field(default=PlanStatus.DRAFT)
    
    # Brain's reasoning (for observability)
    reasoning: str = Field(..., description="Why this plan was chosen")
    alternatives_considered: List[str] = Field(default_factory=list, description="Other plans rejected")
    simulation_results: Optional[Dict[str, Any]] = Field(None, description="Simulation outputs")
    
    # Success criteria
    success_criteria: List[str] = Field(default_factory=list)
    expected_outcome: Optional[Dict[str, Any]] = None
    
    # Fallback & error handling
    fallback_plan_id: Optional[str] = Field(None, description="Alternative plan if this fails")
    max_execution_time_seconds: Optional[int] = None
    
    # Validation
    is_validated: bool = Field(default=False)
    validation_errors: List[str] = Field(default_factory=list)
    
    # Ethics & constraints
    ethics_approved: bool = Field(default=False)
    ethics_notes: Optional[str] = None
    constraints_satisfied: bool = Field(default=True)
    
    # Metadata
    created_at: datetime = Field(default_factory=datetime.now)
    created_by: str = Field(default="brain")
    updated_at: datetime = Field(default_factory=datetime.now)
    version: int = Field(default=1)
    
    # Results (filled as plan executes)
    completed_steps: List[str] = Field(default_factory=list)
    step_results: Dict[str, ToolResult] = Field(default_factory=dict)
    final_output: Optional[Any] = Field(None)


class PlanValidation(BaseModel):
    """Validation result for a plan"""
    is_valid: bool
    errors: List[str] = Field(default_factory=list)
    warnings: List[str] = Field(default_factory=list)
    suggestions: List[str] = Field(default_factory=list)


# ============================================================
# COMMUNICATION MESSAGES
# ============================================================

class ExecutionRequest(BaseModel):
    """
    ExecutionRequest - Wraps a task for network/API transport.
    
    This is the formal "envelope" for sending work to Tentacles.
    """
    request_id: str = Field(..., description="Unique request ID")
    task: TaskRequest
    auth_token: Optional[str] = Field(None, exclude=True)
    timeout_seconds: int = Field(default=300)
    created_at: datetime = Field(default_factory=datetime.now)


class ExecutionResponse(BaseModel):
    """
    ExecutionResponse - Wraps a result for returning to the Brain.
    
    This is the formal "envelope" for returning work from Tentacles.
    """
    request_id: str = Field(..., description="Correlates with ExecutionRequest")
    task_id: str = Field(..., description="Which task this responds to")
    result: ToolResult
    received_at: datetime = Field(default_factory=datetime.now)


# ============================================================
# BRAIN STATE MODELS
# ============================================================

class WorldState(BaseModel):
    """
    WorldState - The Brain's understanding of the current state.
    
    This represents the "world model" maintained by the Brain.
    """
    state_id: str = Field(..., description="Unique state identifier")
    entities: Dict[str, Any] = Field(default_factory=dict)
    relationships: Dict[str, List[str]] = Field(default_factory=dict)
    current_goals: List[str] = Field(default_factory=list)
    active_constraints: List[str] = Field(default_factory=list)
    timestamp: datetime = Field(default_factory=datetime.now)


class BrainThought(BaseModel):
    """
    BrainThought - A single unit of reasoning from the Brain.
    
    For observability: logs the "Slow Thinking" process.
    """
    thought_id: str
    plan_id: Optional[str] = None
    thought_type: str  # perception, reasoning, planning, evaluation, decision
    content: str
    confidence: float = Field(ge=0, le=1)
    timestamp: datetime = Field(default_factory=datetime.now)
    metadata: Dict[str, Any] = Field(default_factory=dict)


# ============================================================
# HELPER FUNCTIONS
# ============================================================

def create_task_request(
    task_id: str,
    tool_id: str,
    parameters: Dict[str, Any],
    priority: TaskPriority = TaskPriority.NORMAL,
    **kwargs
) -> TaskRequest:
    """Factory function to create a TaskRequest with defaults"""
    return TaskRequest(
        task_id=task_id,
        tool_id=tool_id,
        parameters=parameters,
        priority=priority,
        **kwargs
    )


def create_plan(
    plan_id: str,
    objective: str,
    steps: List[ExecutionStep],
    reasoning: str,
    **kwargs
) -> Plan:
    """Factory function to create a Plan with required fields"""
    return Plan(
        plan_id=plan_id,
        objective=objective,
        steps=steps,
        reasoning=reasoning,
        **kwargs
    )


def create_tool_result(
    tool_id: str,
    task_id: str,
    status: TaskStatus,
    output: Any = None,
    **kwargs
) -> ToolResult:
    """Factory function to create a ToolResult"""
    return ToolResult(
        tool_id=tool_id,
        task_id=task_id,
        status=status,
        output=output,
        **kwargs
    )
